# Generated by Django 4.0.3 on 2022-03-15 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom')),
                ('reason', models.TextField(verbose_name='Les raisons')),
                ('accepted', models.BooleanField(default=False, verbose_name='Requête acceptée')),
                ('paid', models.BooleanField(default=False, verbose_name='Remboursé')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse mail du demandeur')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Commande')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Requête de remboursement',
                'verbose_name_plural': 'Requêtes de remboursement',
                'ordering': ['paid', 'accepted', 'date', 'user'],
            },
        ),
    ]
