# Generated by Django 4.0.3 on 2022-03-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refunds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='refused',
            field=models.BooleanField(default=False, verbose_name='Réfusée'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Remboursée'),
        ),
    ]
