# Generated by Django 4.0.3 on 2022-03-20 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_order_total'),
        ('refunds', '0003_alter_refund_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.order', verbose_name='Commande'),
        ),
    ]
