# Generated by Django 4.0.3 on 2022-03-15 23:11

import ckeditor_uploader.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Nom de la promotion')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Détails de la promotion')),
                ('start_date', models.DateTimeField(verbose_name='Début de la promotion')),
                ('end_date', models.DateTimeField(verbose_name='Fin de la promotion')),
                ('banner', models.ImageField(upload_to='images/promotions/%Y/%m/', verbose_name='Bannière')),
                ('added_on', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_public', models.BooleanField(default=True, verbose_name='Public ?')),
                ('has_expired', models.BooleanField(default=False, verbose_name='A expiré')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'ordering': [],
            },
        ),
    ]
