# Generated by Django 4.0.3 on 2022-03-15 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('is_subscribed', models.BooleanField(default=True, verbose_name='abonné(e)')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Supprimé')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
            options={
                'ordering': ['email', 'date'],
            },
        ),
    ]
