# Generated by Django 4.0.3 on 2022-03-16 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date', 'title', 'is_public'], 'verbose_name': 'Publication', 'verbose_name_plural': 'Publications'},
        ),
    ]
