# Generated by Django 4.0.3 on 2022-03-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(upload_to='images/blog/%Y/%m/', verbose_name='Image'),
        ),
    ]
