# Generated by Django 4.0.3 on 2022-03-15 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='Valeur des dépenses')),
                ('expense_type', models.CharField(max_length=200, verbose_name='Type de dépense')),
                ('reason', models.TextField(verbose_name='Pourquoi ces dépenses ?')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['amount', 'expense_type', 'date'],
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, editable=False, null=True, verbose_name='Valeur de la vente')),
                ('sale_type', models.CharField(editable=False, max_length=200, verbose_name='Type de vente')),
                ('reason', models.TextField(verbose_name='Raisons des ventes')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Vente',
                'ordering': ['amount', 'sale_type', 'date'],
                'get_latest_by': 'date',
            },
        ),
    ]
