# Generated by Django 4.0.3 on 2022-03-15 23:11

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(default='CI', max_length=2, unique=True, verbose_name='Pays de livraison')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Pays de livraison',
                'verbose_name_plural': 'Pays de livraison',
                'ordering': ['country', 'date'],
            },
        ),
        migrations.CreateModel(
            name='ShippingCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200, unique=True, verbose_name='Ville de livraison')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.shippingcountry', verbose_name='Pays')),
            ],
            options={
                'verbose_name': 'Ville de livraison',
                'verbose_name_plural': 'Villes de livraison',
                'ordering': ['city', 'country', 'date'],
            },
        ),
    ]
