# Generated by Django 4.0.3 on 2022-03-16 20:38

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='Question')),
                ('answer', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Réponse')),
                ('is_public', models.BooleanField(default=True, verbose_name='Public')),
                ('slug', models.SlugField(max_length=400, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
            ],
            options={
                'verbose_name': 'Qestion/Réponse',
                'verbose_name_plural': 'Qestions/Réponses',
                'ordering': ['question', 'date'],
            },
        ),
    ]
