# Generated by Django 4.0.3 on 2022-03-15 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='N° de tel')),
                ('unique_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('avatar', models.ImageField(blank=True, default='default/user.png', null=True, upload_to='images/profils/avatars/%Y/%m/', verbose_name='Photo de profil')),
                ('signup_lat_long', models.CharField(blank=True, max_length=50, null=True, verbose_name="Coordonnées (à l'inscription)")),
                ('signup_hostname', models.CharField(blank=True, max_length=1000, null=True, verbose_name="Appareil (à l'inscription)")),
                ('signup_ip', models.CharField(blank=True, max_length=15, null=True, verbose_name="Adresse IP (à l'inscription)")),
                ('signup_browser', models.CharField(blank=True, max_length=1000, null=True, verbose_name="Navigateur (à l'inscription)")),
                ('last_login_lat_long', models.CharField(blank=True, max_length=50, null=True, verbose_name='Coordonnées (connexion)')),
                ('last_login_hostname', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Appareil (connexion)')),
                ('last_login_ip', models.CharField(blank=True, max_length=15, null=True, verbose_name='Adresse IP (connexion)')),
                ('last_login_browser', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Navigateur (connexion)')),
                ('is_dispatcher', models.BooleanField(default=False, verbose_name='Livreur ?')),
                ('is_dev', models.BooleanField(default=False, verbose_name='Dévéloppeur du site')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('favorite_items', models.ManyToManyField(blank=True, to='products.soap', verbose_name='Articles favoris')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Profil d'utlisateur",
                'verbose_name_plural': 'Profil des utlisateurs',
            },
        ),
    ]
