# Generated by Django 4.0.3 on 2022-03-15 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Code de la commande')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Début de commande')),
                ('ordered_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de commande (fin)')),
                ('ordered', models.BooleanField(default=False, verbose_name='Commande effectuée ?')),
                ('shipping_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de commande')),
                ('shipping_phonenumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='N° tel de livraison')),
                ('shipping_firstname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom')),
                ('shipping_lastname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Prenom(s)')),
                ('get_shipping_total', models.BigIntegerField(default=0, verbose_name='Frais de livraison')),
                ('being_delivered', models.BooleanField(default=False, verbose_name='En cours de livraison')),
                ('received', models.BooleanField(default=False, verbose_name='Livrée')),
                ('refund_requested', models.BooleanField(default=False, verbose_name='Requête de remboursement')),
                ('refund_granted', models.BooleanField(default=False, verbose_name='Requête de remboursement acceptée')),
                ('order_qr_code', models.ImageField(blank=True, null=True, upload_to='images/commandes/qrcodes/%Y/%m/', verbose_name='QR Code')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-id', 'unique_code'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False, verbose_name='Commandé ?')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantité')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Choix de menus',
                'verbose_name_plural': 'Choix de menus',
            },
        ),
    ]
