# Generated by Django 4.0.3 on 2022-03-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_total',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Total TTC'),
        ),
    ]
