# Generated by Django 4.0.3 on 2022-03-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soap',
            name='is_available',
            field=models.CharField(choices=[('En rupture de stock', 'En rupture de stock'), ('Disponible', 'Disponible')], default=('En rupture de stock', 'En rupture de stock'), max_length=20, verbose_name='Disponibilité'),
        ),
        migrations.AlterField(
            model_name='soap',
            name='type',
            field=models.CharField(blank=True, choices=[('all', 'Tout'), ('women', 'Femmes'), ('men', 'Hommes'), ('children', 'Enfants')], default=('all', 'Tout'), max_length=12, null=True, verbose_name='Type de personne'),
        ),
    ]
