# Generated by Django 4.0.3 on 2022-03-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_soap_is_available_alter_soap_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soap',
            name='is_available',
            field=models.CharField(choices=[('En rupture de stock', 'En rupture de stock'), ('Disponible', 'Disponible')], default=('Disponible', 'Disponible'), max_length=20, verbose_name='Disponibilité'),
        ),
    ]
